# Generated by Django 2.0.3 on 2018-05-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20180420_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.AlterField(
            model_name='product',
            name='caracteristicas',
            field=models.ManyToManyField(related_name='productos', through='base.Features', to='base.Feature'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredientes',
            field=models.ManyToManyField(related_name='productos', through='base.Supplies', to='base.Supply'),
        ),
    ]
