# Generated by Django 2.0.3 on 2018-05-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
