# Generated by Django 2.0.3 on 2018-05-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20180506_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caracteristicas',
            field=models.ManyToManyField(related_name='caracteristicas', through='base.Features', to='base.Feature'),
        ),
    ]
