# Generated by Django 2.0.3 on 2018-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20180514_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredientes',
            field=models.ManyToManyField(related_name='products', through='base.Supplies', to='base.Supply'),
        ),
    ]
