# Generated by Django 2.0.3 on 2018-05-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20180514_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
