# Generated by Django 2.0.3 on 2018-05-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20180528_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='suppliespurchase',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='suppliespurchase',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='$'),
        ),
    ]
