# Generated by Django 2.0.3 on 2018-05-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20180529_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='suplier',
        ),
        migrations.AddField(
            model_name='purchase',
            name='suplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Supplier'),
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
