# Generated by Django 2.0.3 on 2018-05-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20180529_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='suplier',
            new_name='supplier',
        ),
    ]
