# Generated by Django 2.0.3 on 2018-05-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20180529_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='precio_total',
            new_name='costo_total',
        ),
        migrations.AddField(
            model_name='order',
            name='precio_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
