# Generated by Django 2.0.3 on 2018-05-31 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20180529_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ordenes',
        ),
        migrations.AddField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Client'),
        ),
    ]
