# Generated by Django 2.0.5 on 2018-05-31 21:32

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20180531_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_image_path),
        ),
    ]
