# Generated by Django 2.0.5 on 2018-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20180604_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
