# Generated by Django 2.0.5 on 2018-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20180605_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredientes',
            field=models.ManyToManyField(related_name='ingredientes', through='base.Supplies', to='base.Supply'),
        ),
    ]
