# Generated by Django 2.0.5 on 2018-06-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20180605_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='saldo_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
