# Generated by Django 2.0.5 on 2018-06-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_product_horas_trabajadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_hora_trabajada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_pasteleria', models.CharField(max_length=70)),
            ],
        ),
    ]
