# Generated by Django 2.0.5 on 2018-06-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_systemparameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cantidad',
        ),
    ]
