# Generated by Django 2.0.3 on 2018-03-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsFeatures',
            new_name='ProductFeature',
        ),
    ]
