# Generated by Django 2.0.3 on 2018-04-01 23:14

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180331_1631'),
    ]

    operations = [
        migrations.RenameField('Feature', 'nombre_caract', 'nombre'),
        migrations.AddField('Feature', 'tipo', models.CharField(max_length = 70, default=''))
    ]
