# Generated by Django 2.0.3 on 2018-04-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180401_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VT', 'Venta'), ('CP', 'Compra')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('dirección', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('marca', models.CharField(max_length=70)),
                ('tipo', models.CharField(max_length=70)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidad', models.CharField(choices=[('KG', 'Kilo'), ('UN', 'Unidad'), ('LT', 'Litro')], default=None, max_length=2)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductFeature',
        ),
        migrations.AlterField(
            model_name='feature',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='feature',
            name='tipo',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
