# Generated by Django 2.0.3 on 2018-04-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180404_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('dirección', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocasion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contacto',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='supply',
            name='proveedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Supplier'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='fecha',
            field= models.DateField('Fecha de la operación', auto_now=False)
        ),
        migrations.AddField(
            model_name='order',
            name='ingredientes_utilizados',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Supply'),
        ),
        migrations.AddField(
            model_name='client',
            name='pedido',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Order'),
        ),
    ]
