# Generated by Django 2.0.3 on 2018-04-04 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180404_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la operación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 4, 4, 16, 26, 5, 324367, tzinfo=utc), verbose_name='Fecha de pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='tipo',
            field=models.CharField(choices=[('VT', 'Venta'), ('CP', 'Compra')], default='VT', max_length=2),
        ),
        migrations.AlterField(
            model_name='supply',
            name='unidad',
            field=models.CharField(choices=[('KG', 'Kilo'), ('UN', 'Unidad'), ('LT', 'Litro')], default='KG', max_length=2),
        ),
        migrations.AlterField(
            model_name='supply',
            name='movimiento',
            field= models.ForeignKey(blank = True, on_delete=django.db.models.deletion.CASCADE,to= 'base.Movement', default = 'COMPRA' ),
        ),
    ]
