# Generated by Django 2.0.3 on 2018-04-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180404_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Movement'),
        ),
    ]
