# Generated by Django 2.0.3 on 2018-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_supply_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
