# Generated by Django 2.0.3 on 2018-04-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_supply_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cantidad',
        ),
    ]
