# Generated by Django 2.0.3 on 2018-04-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_feature_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='movimiento',
        ),
        migrations.AddField(
            model_name='feature',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='$'),
        ),
        migrations.AddField(
            model_name='movement',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Supply'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='supply',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Supplier'),
        ),
    ]
