# Generated by Django 2.0.3 on 2018-04-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180405_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='producto',
            new_name='supply',
        ),
    ]
