# Generated by Django 2.0.3 on 2018-05-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180502_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='descripcion',
            field=models.TextField(max_length=140, null=True),
        ),
    ]
