# Generated by Django 2.0.3 on 2018-05-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180502_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
