# Generated by Django 2.0.3 on 2018-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180405_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
