# Generated by Django 2.0.3 on 2018-04-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_purchase_precio_unitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='proveedor',
        ),
    ]
