# Generated by Django 2.0.3 on 2018-05-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_client_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Order'),
        ),
    ]
