# Generated by Django 2.0.3 on 2018-04-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_supply_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Purchase'),
        ),
        migrations.AddField(
            model_name='movement',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Sale'),
        ),
    ]
