# Generated by Django 2.0.3 on 2018-05-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20180502_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SuppliesMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='pedido',
            new_name='ordenes',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ingredientes_utilizados',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='suplier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='producto',
        ),
        migrations.AddField(
            model_name='suppliesmovement',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Movement'),
        ),
        migrations.AddField(
            model_name='suppliesmovement',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Supply'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Movement'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Supplier'),
        ),
        migrations.AddField(
            model_name='products',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Order'),
        ),
        migrations.AddField(
            model_name='products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Product'),
        ),
        migrations.AddField(
            model_name='movement',
            name='suply',
            field=models.ManyToManyField(related_name='suplies', through='base.SuppliesMovement', to='base.Supply'),
        ),
        migrations.AddField(
            model_name='movement',
            name='suplier',
            field=models.ManyToManyField(related_name='supliers', through='base.Suppliers', to='base.Supplier'),
        ),
        migrations.AddField(
            model_name='order',
            name='producto',
            field=models.ManyToManyField(related_name='productos', through='base.Products', to='base.Product'),
        ),
    ]
