# Generated by Django 2.0.3 on 2018-04-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20180405_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='fecha',
            field=models.DateField(null=True, verbose_name='fecha de compra'),
        ),
    ]
