# Generated by Django 2.0.3 on 2018-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_suppliesmovement_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha de la operación'),
        ),
    ]
