# Generated by Django 2.0.3 on 2018-04-16 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_purchase_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='venta',
        ),
        migrations.AddField(
            model_name='movement',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='movement',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Order'),
        ),
        migrations.AddField(
            model_name='movement',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Product'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
