# Generated by Django 2.0.3 on 2018-04-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20180416_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supply',
            field=models.ManyToManyField(to='base.Supply'),
        ),
    ]
