# Generated by Django 2.0.3 on 2018-05-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20180510_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='producto',
        ),
        migrations.AddField(
            model_name='productssale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='producto',
            field=models.ManyToManyField(related_name='saleproducto', through='base.ProductsSale', to='base.Product'),
        ),
    ]
