# Generated by Django 2.0.3 on 2018-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20180514_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cantidad',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
