# Generated by Django 2.0.3 on 2018-05-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_order_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='products',
            name='cantidad',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
