# Generated by Django 2.0.3 on 2018-05-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20180529_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productssale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productssale',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ProductsSale',
        ),
    ]
