# Generated by Django 2.0.3 on 2018-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20180529_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='precio',
        ),
        migrations.AddField(
            model_name='order',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
