# Generated by Django 2.0.5 on 2018-06-03 18:03

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_feature_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='repuestos',
        ),
        migrations.RemoveField(
            model_name='autoparte',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='autoparte',
            name='repuesto',
        ),
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_image_path),
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.DeleteModel(
            name='Autoparte',
        ),
        migrations.DeleteModel(
            name='Repuesto',
        ),
    ]
