# Generated by Django 2.0.5 on 2018-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20180603_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='saldo_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
